---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-6.5
    driver: 
        box: centos-6.5
        box_url: https://vagrantcloud.com/baremettle/centos-6.5/version/1/provider/libvirt.box

suites:
  - name: default
    run_list:
    attributes:
